### ISSUE TITLE
Reproduce Hybrid nDCG@10

### ISSUE THREAD

**Issue by zhiqihuang** [project-miracl/miracl#11]
Hi,

I tried to reproduce hybrid ndcg@10 but got different numbers. Take Spanish as an example:

- I reproduced the BM25 (0.3193) and mDPR (0.4777), which match the numbers in the paper.

- And then, I normalized the BM25 and mDPR scores using MinMaxScaler from sklearn, respectively.

- Finally, sum the BM25 and mDPR scores by setting alpha = 0.5 but the ndcg@10 from my hybrid list is 0.5638

What am I missing here?

Thank you!

**Comment by crystina-z** [comment]
Hi @zhiqihuang, I believe we only use the first part in the MinMaxScalar:
```
X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
```

also here's the command I was using to produce the hybrid runfile, with `pyserini`, let me know if it works for you:
```
 python -m pyserini.fusion --runs ${bm25_runfile} ${mdpr_runfile}--output ${fusion_runfile} --method interpolation --alpha 0.5 --depth 1000 --k 1000
```

**Comment by zhiqihuang** [comment]
> Hi @zhiqihuang, I think we only use the first part in the MinMaxScalar:
> 
> ```
> X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
> ```
> 
> also here's the command I was using to produce the hybrid runfile, with `pyserini`, lmk if it works for you:
> 
> ```
>  python -m pyserini.fusion --runs ${bm25_runfile} ${mdpr_runfile}--output ${fusion_runfile} --method interpolation --alpha 0.5 --depth 1000 --k 1000
> ```

Strange. I changed my normalization function and used the same pyserini command, got 0.5623

**Comment by crystina-z** [comment]
@zhiqihuang I realized in the [2CR](https://castorini.github.io/pyserini/2cr/miracl.html) (if that's what you used to reproduce), `hits` is set to 100, which means running the above command (`python -m pyserini.fusion ...`) on it only performs hybrid on top-100 results rather than 1k as specified in the command. Could that be the issue?

**Comment by zhiqihuang** [comment]
Yes, I use 2CR with hits = 100. That could be the issue. I will set hits to 1K for both BM25 and mDPR, then try again.

**Comment by zhiqihuang** [comment]
@crystina-z Set `hits` to 1000 for both BM25 and mDPR gives 0.6355. I think this is within the tolerance range. Thanks for your help.
