### ISSUE TITLE
mDPR training script and triplets

### ISSUE THREAD

**Issue by littlewine** [project-miracl/miracl#13]
Hi and thanks for organizing the challenge and creating the baselines.

Is the training script of mDPR and the training triples available somewhere?

If I am not mistaken the original reference for mDPR was "Towards Best Practices for Training Multilingual Dense Retrieval Models". I can find some details about the training on Sec 3.2 of the paper, and it also mentions the model was trained using tevatron, instead of the original DPR implementation.

Can you also provide more details on which training triples were used for training this model (for MSMarco `castorini/mdpr-tied-pft-msmarco`, but also how the finetuned versions triples were made)? 

Thanks a lot!

**Comment by crystina-z** [comment]
Hi @littlewine thanks for your interest in MRIACL! 

Yes the mDPR is trained using Tevatron, following their example: https://github.com/texttron/tevatron/blob/main/examples/example_msmarco.md. 
The triplet is also prepared by the Tevatron team [here](https://huggingface.co/datasets/Tevatron/msmarco-passage), I believe the negative is sampled from BM25.

**Comment by littlewine** [comment]
Thank you @crystina-z

**Comment by orionw** [comment]
Hi, sorry to reopen this. 

@crystina-z could you comment more on this? Is it an **exact** replica of their example? The MIRACL paper is vague on what this baseline is and I can't find a script to reproduce its training (or data) except for that example.

For example, the links you reference are to an English MSMarco. I thought `castorini/mdpr-tied-pft-msmarco` was multilingual? And if not, what is the "m" in "mdpr"?

Sorry for the naive questions and thanks for your time.

**Comment by crystina-z** [comment]
Hi @orionw yes I believe that is an exact replica, the training data indeed only include the English MS MARCO, whereas the `m` in `mdpr` represents multilingual backbone, which is mBERT here

**Comment by orionw** [comment]
Thank you! Makes sense, appreciate the help!
