### ISSUE TITLE
can't run the scripts with test set

### ISSUE THREAD

**Issue by miaaazhang** [project-miracl/miracl#14]
Hi, I followed the instruction in the README, downloading and putting the datasets in the right place.
However, I cannot get it run with test-a set. I used the commands as follows:
```
python -m pyserini.search.lucene   --language ar   --topics miracl-v1.0-ar-test-a   --index miracl-v1.0-ar   --output run.miracl.bm25.ar.dev.txt
```
It raised with: 
ValueError: Topic miracl-v1.0-ar-test-a Not Found

**Comment by ToluClassics** [comment]
Hi @miaaazhang, sorry about that.

You need to download the queries and pass it as a file path to Pyserini instead


python -m pyserini.search.lucene   --language ar   --topics /path/to/miracl-v1.0-ar-test-a   --index miracl-v1.0-ar   --output run.miracl.bm25.ar.dev.txt

**Comment by miaaazhang** [comment]
> Hi @miaaazhang, sorry about that.
> 
> You need to download the queries and pass it as a file path to Pyserini instead
> 
> python -m pyserini.search.lucene --language ar --topics /path/to/miracl-v1.0-ar-test-a --index miracl-v1.0-ar --output run.miracl.bm25.ar.dev.txt

Thank you! It works! 
BTW,  I still have another question about reproducing your baseline results.
I used the codes below to generate the predictions:
```
lang = "bn"
searcher = LuceneSearcher.from_prebuilt_index(f'miracl-v1.0-{lang}')
miracl_dataset = datasets.load_dataset('miracl/miracl', lang,
                                       use_auth_token=access_token)
miracl_dataset_split = miracl_dataset['dev']
hits = []
for query in miracl_dataset_split['query']:
    ihit = searcher.search(query,k=top_k)
    tmp = [{"docid":ele.docid,"score":ele.score} for ele in ihit]
    hits.append(tmp)
```
But I cannot get the baseline results on the leaderboard. And I find the results are different from those generated from the codes below:
```
python -m pyserini.search.lucene \
  --language bn \
  --topics miracl-v1.0-bn-dev \
  --index miracl-v1.0-bn \
  --output run.miracl.bm25.bn.dev.txt \
  --batch 128 --threads 16 --bm25 --hits 100
```
What's the difference between the two ways of result generation? 
Waiting for your explanation.
Thank you in advance and Happy New Year!

**Comment by ToluClassics** [comment]
Hi @miaaazhang, are you able to get the baseline results using the second code snippet?

For the LuceneSearcher, I believe you have to set the language for the searcher using `searcher.set_language("bn")` otherwise it uses the default English Analyzer to process the queries which might be responsible for the discrepancies.

```
lang = "bn"
searcher = LuceneSearcher.from_prebuilt_index(f'miracl-v1.0-{lang}')
searcher.set_language(lang)
miracl_dataset = datasets.load_dataset('miracl/miracl', lang,
                                       use_auth_token=access_token)
miracl_dataset_split = miracl_dataset['dev']
hits = []
for query in miracl_dataset_split['query']:
    ihit = searcher.search(query,k=top_k)
    tmp = [{"docid":ele.docid,"score":ele.score} for ele in ihit]
    hits.append(tmp)
```

**Comment by miaaazhang** [comment]
> Hi @miaaazhang, are you able to get the baseline results using the second code snippet?
> 
> For the LuceneSearcher, I believe you have to set the language for the searcher using `searcher.set_language("bn")` otherwise it uses the default English Analyzer to process the queries which might be responsible for the discrepancies.
> 
> ```
> lang = "bn"
> searcher = LuceneSearcher.from_prebuilt_index(f'miracl-v1.0-{lang}')
> searcher.set_language(lang)
> miracl_dataset = datasets.load_dataset('miracl/miracl', lang,
>                                        use_auth_token=access_token)
> miracl_dataset_split = miracl_dataset['dev']
> hits = []
> for query in miracl_dataset_split['query']:
>     ihit = searcher.search(query,k=top_k)
>     tmp = [{"docid":ele.docid,"score":ele.score} for ele in ihit]
>     hits.append(tmp)
> ```

It works. Thank you! @ToluClassics
