### ISSUE TITLE
Slack invite link no longer active

### ISSUE THREAD

**Issue by nickchomey** [project-miracl/miracl#15]
Is your slack still active? If so, could you please update the link here and on your [homepage](https://project-miracl.github.io/)?

**Comment by crystina-z** [comment]
Hi @nickchomey sorry for the late reply, the slack link is now updated -- I also pasted it here https://join.slack.com/t/miraclgroup/shared_invite/zt-1ph43qw40-gvoQI~jc_g2EPb_EgCF4Dg
