### ISSUE TITLE
which checkpoint is used in the mDPR baseline

### ISSUE THREAD

**Issue by searchivarius** [project-miracl/miracl#16]
Hi, thank you for sharing this wonderful resource!

Could you clarify which HF checkpoint is used for mDPR baseline? There are several candidate available, I tried several and my latest suspicion is that it's : castorini/mdpr-tied-pft-msmarco ? Is it correct? Is it stated somewhere?

**Comment by crystina-z** [comment]
Hi! Thanks for your interest in MIRACL!

Correct the mDPR baseline is prepared using castorini/mdpr-tied-pft-msmarco. 
The indexes are available in Pyserini, and we have a "two-click-reproduce" website set up for the baselines: https://castorini.github.io/pyserini/2cr/miracl.html
Hope that helps!

**Comment by searchivarius** [comment]
Thank you for clarifying: is it possible to state explicitly somewhere? There are multiple reasons to use other indexes beyond provided ones, plus, the model can be potentially finetuned.

**Comment by crystina-z** [comment]
yea that make sense. thanks for the suggestion! the checkpoints are now added in the README: https://github.com/project-miracl/miracl#checkpoints-for-dense-models
