### ISSUE TITLE
Scripts to create corpus from a Wikipedia dump

### ISSUE THREAD

**Issue by ftvalentini** [project-miracl/miracl#17]
Hi! 

I was wondering if you have the scripts to prepare the corpus of a given language from the raw wiki dump, that is, to perform [this](https://github.com/project-miracl/miracl/blob/0e947891b0672cade00e7197dcf9457a9e961d31/README.md?plain=1#L69-72):

"The corpus for each language is prepared from a Wikipedia dump, where we keep only the plain text and discard images, tables, etc. Each article is segmented into multiple passages using WikiExtractor based on natural discourse units (e.g., \n\n in the wiki markup). Each of these passages comprise a "document" or unit of retrieval. We preserve the Wikipedia article title of each passage."

Thanks and cheers!

**Comment by crystina-z** [comment]
Hi @ftvalentini! Sure, I don't have the one preparing MIRACL corpus online, but it's mostly pretty similar to the logic we used for Mr. TyDi:
1) [script for download and extract](https://github.com/crystina-z/mrtydi-codebase/blob/master/prep_data_from_tydi/0_download_and_extract.wiki.sh)
2) [script to prepare passages](https://github.com/crystina-z/mrtydi-codebase/blob/master/prep_data_from_tydi/7_convert_to_hgf_format.py#L24-L31)

Hope they are useful and lmk if there are further questions!

**Comment by ftvalentini** [comment]
That's great @crystina-z, thank you so much!!
