### ISSUE TITLE
When searching for the top-k results, are we supposed to use only the title in the corpus, or the title and text concatenated together?

### ISSUE THREAD

**Issue by steven-channel** [project-miracl/miracl#18]
I'm seeing varying results from different implementations online. What is the standard way of performing evaluation on MIRACL? Thanks.

**Comment by lintool** [comment]
Start with Pyserini here for the reference implementation: https://castorini.github.io/pyserini/2cr/miracl.html

**Comment by steven-channel** [comment]
Thanks. I've checked the source code for the MIRACL evaluation on Pyserini, but I don't believe there's any code for the actual corpus encoding itself; it seems you guys are providing pre-built FAISS indexes. I'm assuming that the title and text were both used for the document representation, but just wanted to be sure.

**Comment by lintool** [comment]
For corpus encoding, we'll have ask @crystina-z to clarify.

**Comment by crystina-z** [comment]
heyy @steven-channel you are right, both title and text were used. Commands to produce the released index can be found here: https://github.com/castorini/pyserini/blob/master/pyserini/resources/index-metadata/faiss.miracl-v1.0.20221004.2b2856.mdpr-tied-pft-msmarco-ft-all.README.md

**Comment by steven-channel** [comment]
@crystina-z Thanks for clarifying! I'll take a look at the code and corpus.

**Comment by zanussbaum** [comment]
@crystina-z is it possible to add this to the README? it took me a while to figure out exactly how to get the data and how to generate an index. I'm sure this would help a ton of people!

**Comment by crystina-z** [comment]
Thanks for the suggestion @zanussbaum! It's now in Readme
