### ISSUE TITLE
Passages truncated to 256 tokens?

### ISSUE THREAD

**Issue by ftvalentini** [project-miracl/miracl#19]
From the scripts to reproduce the dense indices of the documents (wiki paragraphs):

https://github.com/castorini/pyserini/blob/1219cdbca780e869ba77658c29e1aaa972585d09/pyserini/resources/index-metadata/faiss.miracl-v1.0.20221004.2b2856.mdpr-tied-pft-msmarco.README.md

It seems that you have used the default max-length from `pyserini.encode` which seems to be 256: 

https://github.com/castorini/pyserini/blob/b7e1da305dd31b195244d49321087505996260c6/pyserini/encode/__main__.py#L121

Even if the max_length of the base model used (BERT) is 512 (https://huggingface.co/castorini/mdpr-tied-pft-msmarco-ft-miracl-es/blob/main/tokenizer_config.json).

Am I getting this right? There might be paragraphs in wikipedia longer than 256 tokens and it might not be a good idea to truncate them. 

Thank you very much for such a great resource!

**Comment by crystina-z** [comment]
Hi @ftvalentini! Thanks for your interest in MIRACL! yes we use the default length 256 for the encoding
